### ISSUE TITLE
Some NPM packages require a gcc/g++ build environment to install via node-gyp

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/containers-quickstarts#207]
Does it make sense for us to install the following items as well, so that we can build/install NPM packages which require a natively compiled binary?

`yum install gcc-c++` and `yum groupinstall 'Development Tools'` 

https://github.com/redhat-cop/containers-quickstarts/blob/9f719f66e3c5ed78d9c013692c796700a778edbd/jenkins-slaves/jenkins-slave-npm/Dockerfile.rhel7#L20

**Comment by InfoSec812** [comment]
It looks like fibers tried to install a pre-compiled binary, but that binary failed to work on RHEL7 (SELinux perhaps?)

```
> fibers@3.1.1 install /tmp/workspace/labs-ci-cd/labs-ci-cd-itcm-ngm-ui-pipeline/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-64-glibc` exists; testing
Problem with the binary; manual build incoming
make: Entering directory `/tmp/workspace/labs-ci-cd/labs-ci-cd-itcm-ngm-ui-pipeline/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
make: g++: Command not found
make: *** [Release/obj.target/fibers/src/fibers.o] Error 127
make: Leaving directory `/tmp/workspace/labs-ci-cd/labs-ci-cd-itcm-ngm-ui-pipeline/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-957.5.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /tmp/workspace/labs-ci-cd/labs-ci-cd-itcm-ngm-ui-pipeline/node_modules/fibers
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm WARN vue-authenticate@1.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@3.1.1 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@3.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2019-04-24T13_37_04_832Z-debug.log
```
