### ISSUE TITLE
jenkins-agent-ruby failing to build

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/containers-quickstarts#547]
```
Downloading Jenkins logs for jenkins-agent-ruby-pipeline-1 as phase (Failed) does not match expected (Complete)...
## START LOGS: jenkins-agent-ruby-pipeline-1
OpenShift Build cqci-838cc197-7902-11ec-8622-0a580a83000f/jenkins-agent-ruby-pipeline-1 from https://github.com/eformat/containers-quickstarts.git
Checking out git https://github.com/eformat/containers-quickstarts.git into /var/lib/jenkins/jobs/cqci-838cc197-7902-11ec-8622-0a580a83000f/jobs/cqci-838cc197-7902-11ec-8622-0a580a83000f-jenkins-agent-ruby-pipeline/workspace@script to read jenkins-agents/jenkins-agent-ruby/Jenkinsfile.test
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/eformat/containers-quickstarts.git
 > git init /var/lib/jenkins/jobs/cqci-838cc197-7902-11ec-8622-0a580a83000f/jobs/cqci-838cc197-7902-11ec-8622-0a580a83000f-jenkins-agent-ruby-pipeline/workspace@script # timeout=10
Fetching upstream changes from https://github.com/eformat/containers-quickstarts.git
 > git --version # timeout=10
 > git fetch --tags --progress -- https://github.com/eformat/containers-quickstarts.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/eformat/containers-quickstarts.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/eformat/containers-quickstarts.git # timeout=10
Fetching upstream changes from https://github.com/eformat/containers-quickstarts.git
 > git fetch --tags --progress -- https://github.com/eformat/containers-quickstarts.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse a79ed59a319db7ce424dca4cf7a04c6ac084954d^{commit} # timeout=10
Checking out Revision a79ed59a319db7ce424dca4cf7a04c6ac084954d (detached)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a79ed59a319db7ce424dca4cf7a04c6ac084954d # timeout=10
Commit message: "🌶️ argocd 2.2.3 🌶️"
First time build. Skipping changelog.
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Still waiting to schedule task
‘jenkins-agent-ruby-00ncz’ is offline
Agent jenkins-agent-ruby-d6p8k is provisioned from template jenkins-agent-ruby
---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    jenkins/label-digest: "1eb77c1e0a3eb3b8c51fe94324759becafb7bc76"
    jenkins/label: "jenkins-agent-ruby"
  name: "jenkins-agent-ruby-d6p8k"
spec:
  containers:
  - args:
    - "********"
    - "jenkins-agent-ruby-d6p8k"
    env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_TUNNEL"
      value: "172.30.7.79:50000"
    - name: "JENKINS_AGENT_NAME"
      value: "jenkins-agent-ruby-d6p8k"
    - name: "JENKINS_NAME"
      value: "jenkins-agent-ruby-d6p8k"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/tmp"
    - name: "JENKINS_URL"
      value: "http://172.30.97.192:80/"
    image: "image-registry.openshift-image-registry.svc:5000/cqci-838cc197-7902-11ec-8622-0a580a83000f/jenkins-agent-ruby"
    imagePullPolicy: "Always"
    name: "jnlp"
    resources:
      limits: {}
      requests: {}
    tty: false
    volumeMounts:
    - mountPath: "/tmp"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/tmp"
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  serviceAccount: "jenkins"
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"

Running on jenkins-agent-ruby-d6p8k in /tmp/workspace/cqci-838cc197-7902-11ec-8622-0a580a83000f/cqci-838cc197-7902-11ec-8622-0a580a83000f-jenkins-agent-ruby-pipeline
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/eformat/containers-quickstarts.git
 > git init /tmp/workspace/cqci-838cc197-7902-11ec-8622-0a580a83000f/cqci-838cc197-7902-11ec-8622-0a580a83000f-jenkins-agent-ruby-pipeline # timeout=10
Fetching upstream changes from https://github.com/eformat/containers-quickstarts.git
 > git --version # timeout=10
 > git fetch --tags --force --progress -- https://github.com/eformat/containers-quickstarts.git +refs/heads/*:refs/remotes/origin/* # timeout=10
Checking out Revision a79ed59a319db7ce424dca4cf7a04c6ac084954d (detached)
 > git config remote.origin.url https://github.com/eformat/containers-quickstarts.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/eformat/containers-quickstarts.git # timeout=10
Fetching upstream changes from https://github.com/eformat/containers-quickstarts.git
 > git fetch --tags --force --progress -- https://github.com/eformat/containers-quickstarts.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse a79ed59a319db7ce424dca4cf7a04c6ac084954d^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a79ed59a319db7ce424dca4cf7a04c6ac084954d # timeout=10
Commit message: "🌶️ argocd 2.2.3 🌶️"
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Run Test)
[Pipeline] sh
+ ruby -v
ruby 2.6.7p197 (2021-04-05 revision 67941) [x86_64-linux]
+ gem install rdoc
Building native extensions. This could take a while...
ERROR:  Error installing rdoc:
	ERROR: Failed to build gem native extension.

    current directory: /home/jenkins/.gem/ruby/gems/psych-4.0.3/ext/psych
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20220119-234-encnms.rb extconf.rb
checking for yaml.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--with-libyaml-dir
	--without-libyaml-dir
	--with-libyaml-include
	--without-libyaml-include=${libyaml-dir}/include
	--with-libyaml-lib
	--without-libyaml-lib=${libyaml-dir}/lib64
	--enable-bundled-libyaml
	--disable-bundled-libyaml
/usr/share/ruby/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/share/ruby/mkmf.rb:601:in `try_cpp'
	from /usr/share/ruby/mkmf.rb:1162:in `block in find_header'
	from /usr/share/ruby/mkmf.rb:959:in `block in checking_for'
	from /usr/share/ruby/mkmf.rb:361:in `block (2 levels) in postpone'
	from /usr/share/ruby/mkmf.rb:331:in `open'
	from /usr/share/ruby/mkmf.rb:361:in `block in postpone'
	from /usr/share/ruby/mkmf.rb:331:in `open'
	from /usr/share/ruby/mkmf.rb:357:in `postpone'
	from /usr/share/ruby/mkmf.rb:958:in `checking_for'
	from /usr/share/ruby/mkmf.rb:1161:in `find_header'
	from extconf.rb:10:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/jenkins/.gem/ruby/extensions/x86_64-linux/2.6.0/psych-4.0.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/jenkins/.gem/ruby/gems/psych-4.0.3 for inspection.
Results logged to /home/jenkins/.gem/ruby/extensions/x86_64-linux/2.6.0/psych-4.0.3/gem_make.out
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
## END LOGS: jenkins-agent-ruby-pipeline-1
```

**Comment by garethahealy** [comment]
@redhat-cop/day-in-the-life any ruby devs?
